links:
  home: "home"
  help: "help"
  login: "#"
  rails:
    url: "https://www.railstutorial.org"
    book: "https://www.railstutorial.org/book"
    help: "https://www.railstutorial.org/help"
user:
  name:
    type: string
    max_length: 50
    min_length: 5
  email:
    type: string
    valid: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
    max_length: 255
    min_length: 5
  password:
    digits:
      digit_6: 6
  image:
    profile: 90
    list: 50
  password_reset_expired: 2
page_10: 10
digit_140: 140
digit_50: 50
micropost:
  image:
    width: 500
    height: 500
    max_size: 5
    allowed_types:
      - image/jpeg
      - image/gif
      - image/png
digit_30: 30
